import Projeto from "../models/projeto";

const projetos: Projeto[] = [
  {
    id: 1,
    name: "Go.planner",
    desc: "Uma plataforma interativa desenvolvida para tornar o  planejamento de viagens mais simples e divertido.",
    image: "/images/projects/go.planner.png",
    stacks: ["Figma", "Next.js", "Node.js", "Typescript", "MongoDB"],
    linkProjects: ["https://www.figma.com/design/D3c6UkWiO15EMirUcJVgJq/Go.planner?node-id=0-1&t=Z7ceV9FSZVvdSTEI-1", "https://github.com/R4ULz/go-planner.git", ""],
    software: "yes",
    design: "yes",
  },
  {
    id: 2,
    name: "Krusty Burger",
    desc: "Um sistema do Krusty Burger que simplifica o gerenciamento de pedidos para adms e clientes, oferecendo eficiência e praticidade.",
    image: "/images/projects/krusty-burger.png",
    stacks: ["Figma", "Hadlebars", "Node.js", "MySQL"],
    linkProjects: ["https://www.figma.com/design/Cc3aYFITJuvpNPVjOC1mdb/Krusty-Burguer?t=Z7ceV9FSZVvdSTEI-1", "https://github.com/R4ULz/ProjetoInterdisciplinar-2sem-atualizado.git", ""],
    software: "yes",
    design: "yes",
  },
  {
    id: 3,
    name: "Sneakers",
    desc: "Aplicação interativa que simula a experiência de compra no e-commerce Sneakers, com foco em praticidade e engajamento.",
    image: "/images/projects/sneakers.png",
    stacks: ["Next.js", "Tailwind CSS", "Typescript"],
    linkProjects: ["", "https://github.com/Nick-Yanase/Sneakers.git", "https://sneakers-five-lime.vercel.app"],
    software: "yes", 
    design: "",
  },
  {
    id: 4,
    name: "Meu portfólio",
    desc: "Uma aplicação que apresenta projetos web modernos, destacando habilidades em React, Next.js e soluções inovadoras de design.",
    image: "/images/projects/portfolio.png",
    stacks: ["Figma", "Next.js", "Shadcn/UI", "Tailwind CSS", "Typescript"],
    linkProjects: ["https://www.figma.com/design/8F2YXcqKQzgWa6Iw9IqKwT/Portfolio---nicky?node-id=45-60&t=v66KgHHZcP7RwnmF-1", "https://github.com/Nick-Yanase/portfolio.git", ""],
    software: "yes",
    design: "yes",
  },
  {
    id: 5,
    name: "Sable",
    desc: "Design de uma plataforma financeira: Sable. Crie sua conta de forma rápida e aproveite benefícios exclusivos.",
    image: "/images/projects/sable.png",
    stacks: ["Figma"],
    linkProjects: ["https://www.figma.com/design/euTw4Bo2KkDUo1fPjmj94q/Sable?node-id=0-1&t=Z7ceV9FSZVvdSTEI-1", "", ""],
    software: "",
    design: "yes",
  },
  {
    id: 6,
    name: "Dashboard",
    desc: "Dashboard interativo criado com Next.js e ShadCN, oferecendo visualização eficiente e moderna para dados e insights essenciais.",
    image: "/images/projects/dashboard.png",
    stacks: ["Next.js", "Shadcn/UI", "Tailwind CSS", "Typescript"],
    linkProjects: ["", "https://github.com/Nick-Yanase/dashboard.git", "https://dashboard-rho-flame.vercel.app"],
    software: "yes",
    design: "",
  }, 
  {
    id: 7,
    name: "Ecommerce A-Z",
    desc: "Aplicação de ecommerce, oferecendo uma ampla variedade de produtos, com experiência prática e personalizada.",
    image: "/images/projects/ecommerce-a-z.png",
    stacks: ["Next.js", "Typescript", "Tailwind CSS"],
    linkProjects: ["", "https://github.com/Nick-Yanase/Ecommerce_A-Z.git", "https://ecommerce-a-z.vercel.app"],
    software: "yes",
    design: "",
  },
  {
    id: 8,
    name: "Surya Nursing Home",
    desc: "Design de uma aplicação para agendamento presencial com médicos, simplificando consultas com interface moderna e prática.",
    image: "/images/projects/surya-nursing.png",
    stacks: ["figma"],
    linkProjects: ["https://www.figma.com/design/0qPZJmHnr0cRc6zb57muQL/Surya-Nurshing-Home?node-id=0-1&t=Z7ceV9FSZVvdSTEI-1", "", ""],
    software: "",
    design: "yes",
  }, 
  {
    id: 9,
    name: "Food",
    desc: "Aplicação interativa para restaurantes, facilitando reservas, pedidos e gestão, com foco em praticidade e experiência do usuário",
    image: "/images/projects/food.png",
    stacks: ["HTML5", "CSS3", "JS"],
    linkProjects: ["", "https://github.com/Nick-Yanase/LandingPage-food-deploy.git", "https://landing-page-food-deploy.vercel.app"],
    software: "yes",
    design: "",
  }, 
  {
    id: 10,
    name: "Forms light/dark mode",
    desc: "Aplicação de formulários com modos claro e escuro, oferecendo uma experiência personalizável e acessível.",
    image: "/images/projects/light-dark.png",
    stacks: ["HTML5", "CSS3", "JS"],
    linkProjects: ["", "https://github.com/Nick-Yanase/Pagina-Login-Dark-Light.git", "https://pagina-login-dark-light.vercel.app"],
    software: "yes",
    design: "",
  },
  {
    id: 11,
    name: "Bikcraft",
    desc: "Site de vendas de bicicletas elegantes e modernas, oferecendo modelos exclusivos e uma experiência de compra intuitiva.",
    image: "/images/projects/bikcraft.png",
    stacks: ["HTML5", "CSS3"],
    linkProjects: ["", "https://github.com/Nick-Yanase/bikcraft.git", "https://bikcraft-six-wheat.vercel.app"],
    software: "yes",
    design: "",
  }, 
  {
    id: 12,
    name: "Quero +",
    desc: "Design de Landing page para vendas de salgados, com cardápio variado, pedidos rápidos e entrega para qualquer ocasião.",
    image: "/images/projects/quero+.png",
    stacks: ["Figma"],
    linkProjects: ["https://www.canva.com/design/DAFyQ0Bq6DE/CBjI0fAnLeb8K-YV-G0bKQ/edit?utm_content=DAFyQ0Bq6DE&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton", "", ""],
    software: "",
    design: "yes",
  }, 
 
];

export default projetos;
