import Projeto from "../models/projeto";

const projetos: Projeto[] = [
  {
    id: 16,
    name: "Go.planner - Mobile - FATEC",
    desc: "Trazendo a plataforma go.planner para o ambiente mobile, com uma interface otimizada e recursos adicionais como IA",
    myRole: "Desenvolvedor Mobile e IA & Designer",
    myContributions: [
      "Desenvolvi toda a parte mobile da aplicação utilizando React Native, garantindo uma experiência fluida e responsiva para os usuários.",
      "Implementei funcionalidades de IA para personalizar as recomendações de viagem, utilizando Python para criar modelos de aprendizado de máquina que analisam as preferências dos usuários e sugerem destinos, atividades e roteiros personalizados.",
      "Criei designs modernos e intuitivos para a interface do aplicativo, focando na usabilidade e na experiência do usuário, garantindo que a navegação seja fácil e agradável.",
    ],
    image: "/images/projects/go-planner-mobile.png",
    stacks: ["React Native", "Spring Boot", "IA", "Python"],
    linkProjects: ["https://www.figma.com/design/D3c6UkWiO15EMirUcJVgJq/Go.planner?node-id=1378-2546&t=p1Wh9oq7Dmaaspnt-1", "https://github.com/Bonde-do-tigrinho/Go-Planner-Mobile.git", ""],
    software: true,
    design: true,
  },
  {
    id: 15,
    name: "Buscador de Imóveis - FATEC",
    desc: "Um buscador de imóveis que realiza web scraping em sites de instituições financeiras, reunindo oportunidades de imóveis em leilão ou venda direta em uma única plataforma.",
    myRole: "Desenvolvedor Frontend & Designer",
    myContributions: [
      "Desenvolvi a interface do buscador de imóveis, garantindo uma experiência moderna e responsiva para os usuários.",
      "Implementei funcionalidades de busca e filtragem, permitindo que os usuários encontrem facilmente os imóveis que procuram.",
      "Criei designs intuitivos para a interface do aplicativo, focando na usabilidade e na experiência do usuário, garantindo que a navegação seja fácil e agradável.",
    ],
    image: "/images/projects/buscador-imoveis.png",
    stacks: ["Next.js", "MongoDB", "Docker", "Python"],
    linkProjects: ["https://www.figma.com/design/cmjFKQEqScnIXfEFAs2AQY/Buscador-leil%C3%B5es?node-id=63-266&t=IQJiGyW9z3mowpzZ-1", "https://github.com/LeandroRodrigues061/PI-Motor-de-Busca-4-sem.git", ""],
    software: true,
    design: true,
  },
  {
    id: 14,
    name: "Herohub",
    desc: "Aplicação web para explorar e favoritar heróis do universo dos quadrinhos, com interface moderna, responsiva e funcionalidades avançadas de busca, ordenação e navegação.",
    myRole: "Desenvolvedor Frontend",
    myContributions: [
      "Desenvolvi a interface do Herohub, garantindo uma experiência moderna e responsiva para os usuários.",
      "Implementei funcionalidades avançadas de busca, ordenação e navegação, permitindo que os usuários explorem facilmente os heróis disponíveis na plataforma.",
    ],
    image: "/images/projects/herohub.png",
    stacks: ["Next.js", "API", "Typescript", "Versionamento"],
    linkProjects: ["", "https://github.com/Nick-Yanase/herohub.git", "https://herohub-c7py.vercel.app"],
    software: true,
    design: false,
  },
  {
    id: 5,
    name: "Intranet HSF",
    desc: "Design de uma intranet para o hospital São Francisco, facilitando o acesso a diversas informações úteis.",
    myRole: "Designer",
    myContributions:[
      "Criação de uma intranet para o hospital São Francisco, facilitando o acesso a diversas informações úteis para os colaboradores.",
      "Desenvolvimento de uma interface moderna e intuitiva, garantindo que os usuários possam navegar facilmente e encontrar as informações necessárias de forma rápida e eficiente.",
    ],
    image: "/images/projects/hsf.png",
    stacks: ["Figma"],
    linkProjects: ["https://www.figma.com/design/TuKpyfJX3oHwciIjTjU0YW/intranet-Sagrada-Fam%C3%ADlia--Copy-?node-id=253-617&t=L6a7luPM0RBtdo2P-1", "", ""],
    software: false,
    design: true,
  },
  {
    id: 13,
    name: "Printer Bot",
    desc: "Uma aplicação inteligente desenvolvida para automatizar a coleta de contadores de impressoras, eliminando processos manuais e otimizando o tempo da equipe.",
    myRole: "Desenvolvedor Full Stack & Designer",
    myContributions: [
      "Desenvolvi a interface do Printer Bot, garantindo uma experiência moderna e responsiva para os usuários.",
      "Implementei funcionalidades de automação, permitindo que os usuários coletem facilmente os contadores de impressoras.",
      "Criei designs intuitivos para a interface do aplicativo, focando na usabilidade e na experiência do usuário, garantindo que a navegação seja fácil e agradável.",
    ],
    image: "/images/projects/printer-bot.png",
    stacks: ["Next.js", "Node.js", "Typescript", "Python"],
    linkProjects: ["", "https://github.com/Nick-Yanase/printer-bot.git", "https://www.linkedin.com/posts/nicolas-yanase_automatiza%C3%A7%C3%A3o-que-gera-resultados-reais-activity-7333612548207898626-QQ3v?utm_source=share&utm_medium=member_desktop&rcm=ACoAAEF3GAwBYafo7IJa6m7WL9RpPbMtV5BFcrA"],
    software: true,
    design: false,
  },
  {
    id: 1,
    name: "Go.planner - FATEC",
    desc: "Uma plataforma interativa desenvolvida para tornar o  planejamento de viagens mais simples e divertido.",
    myRole: "Desenvolvedor Frontend & Designer",
    myContributions: [
      "Desenvolvi a interface do Go.planner, garantindo uma experiência moderna e responsiva para os usuários.",
      "Implementei funcionalidades avançadas de planejamento de viagens, permitindo que os usuários explorem facilmente as opções disponíveis.",
    ],
    image: "/images/projects/go.planner.png",
    stacks: ["Figma", "Next.js", "Node.js", "Typescript", "MongoDB"],
    linkProjects: ["https://www.figma.com/design/D3c6UkWiO15EMirUcJVgJq/Go.planner?node-id=0-1&t=Z7ceV9FSZVvdSTEI-1", "https://github.com/R4ULz/go-planner.git", ""],
    software: true,
    design: true,
  },
  {
    id: 2,
    name: "Krusty Burger - FATEC",
    desc: "Um sistema do Krusty Burger que simplifica o gerenciamento de pedidos para adms e clientes, oferecendo eficiência e praticidade.",
    myRole: "Desenvolvedor Frontend & Designer",
    myContributions: [
      "Desenvolvi a interface do Krusty Burger, garantindo uma experiência moderna e responsiva para os usuários.",
      "Implementei funcionalidades de gerenciamento de pedidos, permitindo que os usuários explorem facilmente as opções disponíveis.",
    ],
    image: "/images/projects/krusty-burger.png",
    stacks: ["Figma", "Handlebars", "Node.js", "MySQL"],
    linkProjects: ["https://www.figma.com/design/Cc3aYFITJuvpNPVjOC1mdb/Krusty-Burguer?t=Z7ceV9FSZVvdSTEI-1", "https://github.com/R4ULz/ProjetoInterdisciplinar-2sem-atualizado.git", ""],
    software: true,
    design: true,
  },
  {
    id: 3,
    name: "Sneakers",
    desc: "Aplicação interativa que simula a experiência de compra no e-commerce Sneakers, com foco em praticidade e engajamento.",
    myRole: "Desenvolvedor Frontend",
    myContributions: [
      "Desenvolvi a interface do Sneakers, garantindo uma experiência moderna e responsiva para os usuários.",
      "Implementei funcionalidades de compra, permitindo que os usuários explorem facilmente as opções disponíveis e realizem suas compras de forma rápida e eficiente.",
    ],
    image: "/images/projects/sneakers.png",
    stacks: ["Next.js", "Tailwind CSS", "Typescript"],
    linkProjects: ["", "https://github.com/Nick-Yanase/Sneakers.git", "https://sneakers-five-lime.vercel.app"],
    software: true, 
    design: false,
  },
  {
    id: 4,
    name: "Meu portfolio",
    desc: "Uma aplicação que apresenta projetos web modernos, destacando habilidades em React, Next.js e soluções inovadoras de design.",
    myRole: "Desenvolvedor Frontend & Designer",
    myContributions: [
      "Desenvolvi a interface do meu portfolio, garantindo uma experiência moderna e responsiva para os usuários.",
      "Implementei funcionalidades de navegação e apresentação de projetos, permitindo que os usuários explorem facilmente as opções disponíveis.",
      "Criei designs modernos e intuitivos para a interface do aplicativo, focando na usabilidade e na experiência do usuário, garantindo que a navegação seja fácil e agradável.",
    ],
    image: "/images/projects/portfolio.png",
    stacks: ["Figma", "Next.js", "Shadcn/UI", "Tailwind CSS", "Typescript"],
    linkProjects: ["https://www.figma.com/design/8F2YXcqKQzgWa6Iw9IqKwT/Portfolio---nicky?node-id=45-60&t=v66KgHHZcP7RwnmF-1", "https://github.com/Nick-Yanase/portfolio.git", "https://nicky-portfolio.vercel.app"],
    software: true,
    design: true,
  },
  {
    id: 6,
    name: "Dashboard",
    desc: "Dashboard interativo criado com Next.js e ShadCN, oferecendo visualização eficiente e moderna para dados e insights essenciais.",
    myRole: "Desenvolvedor Frontend",
    myContributions: [
      "Desenvolvi a interface do Dashboard, garantindo uma experiência moderna e responsiva para os usuários.",
      "Implementei funcionalidades de visualização de dados, permitindo que os usuários explorem facilmente as informações disponíveis e obtenham insights de forma rápida e eficiente.",
    ],
    image: "/images/projects/dashboard.png",
    stacks: ["Next.js", "Shadcn/UI", "Tailwind CSS", "Typescript"],
    linkProjects: ["", "https://github.com/Nick-Yanase/dashboard.git", "https://dashboard-rho-flame.vercel.app"],
    software: true,
    design: false,
  }, 
  {
    id: 7,
    name: "Ecommerce A-Z",
    desc: "Aplicação de ecommerce, oferecendo uma ampla variedade de produtos, com experiência prática e personalizada.",
    myRole: "Desenvolvedor Frontend",
    myContributions: [
      "Desenvolvi a interface do Ecommerce A-Z, garantindo uma experiência moderna e responsiva para os usuários.",
      "Implementei funcionalidades de compra, permitindo que os usuários explorem facilmente as opções disponíveis e realizem suas compras de forma rápida e eficiente.",
    ],
    image: "/images/projects/ecommerce-a-z.png",
    stacks: ["Next.js", "Typescript", "Tailwind CSS"],
    linkProjects: ["", "https://github.com/Nick-Yanase/Ecommerce_A-Z.git", "https://ecommerce-a-z.vercel.app"],
    software: true,
    design: false,
  },
  // {
  //   id: 8,
  //   name: "Surya Nursing Home",
  //   desc: "Design de uma aplicação para agendamento presencial com médicos, simplificando consultas com interface moderna e prática.",
  //   image: "/images/projects/surya-nursing.png",
  //   stacks: ["Figma"],
  //   linkProjects: ["https://www.figma.com/design/0qPZJmHnr0cRc6zb57muQL/Surya-Nurshing-Home?node-id=0-1&t=Z7ceV9FSZVvdSTEI-1", "", ""],
  //   software: "",
  //   design: true,
  // }, 
  {
    id: 9,
    name: "Food",
    desc: "Aplicação interativa para restaurantes, facilitando reservas, pedidos e gestão, com foco em praticidade e experiência do usuário",
    myRole: "Desenvolvedor Frontend",
    myContributions: [
      "Desenvolvi a interface do Food, garantindo uma experiência moderna e responsiva para os usuários.",
      "Implementei funcionalidades de reserva e pedidos, permitindo que os usuários explorem facilmente as opções disponíveis e realizem suas reservas ou pedidos de forma rápida e eficiente.",
    ],
    image: "/images/projects/food.png",
    stacks: ["HTML5", "CSS3", "JS"],
    linkProjects: ["", "https://github.com/Nick-Yanase/LandingPage-food-deploy.git", "https://landing-page-food-deploy.vercel.app"],
    software: true,
    design: false,
  }, 
  // {
  //   id: 10,
  //   name: "Forms light/dark mode",
  //   desc: "Aplicação de formulários com modos claro e escuro, oferecendo uma experiência personalizável e acessível.",
  //   image: "/images/projects/light-dark.png",
  //   stacks: ["HTML5", "CSS3", "JS"],
  //   linkProjects: ["", "https://github.com/Nick-Yanase/Pagina-Login-Dark-Light.git", "https://pagina-login-dark-light.vercel.app"],
  //   software: true,
  //   design: "",
  // },
  {
    id: 11,
    name: "Bikcraft",
    desc: "Site de vendas de bicicletas elegantes e modernas, oferecendo modelos exclusivos e uma experiência de compra intuitiva.",
    myRole: "Desenvolvedor Frontend",
    myContributions: [
      "Desenvolvi a interface do Bikcraft, garantindo uma experiência moderna e responsiva para os usuários.",
      "Implementei funcionalidades de navegação e compra, permitindo que os usuários explorem facilmente as opções disponíveis e realizem suas compras de forma rápida e eficiente.",
    ],
    image: "/images/projects/bikcraft.png",
    stacks: ["HTML5", "CSS3"],
    linkProjects: ["", "https://github.com/Nick-Yanase/bikcraft.git", "https://bikcraft-six-wheat.vercel.app"],
    software: true,
    design: false,
  }, 
  {
    id: 12,
    name: "Quero + salgados - FATEC",
    desc: "Design de Landing page para vendas de salgados, com cardápio variado, pedidos rápidos e entrega para qualquer ocasião.",
    myRole: "Designer",
    myContributions: [
      "Criação de uma landing page para vendas de salgados, com cardápio variado, pedidos rápidos e entrega para qualquer ocasião.",
      "Desenvolvimento de uma interface moderna e intuitiva, garantindo que os usuários possam navegar facilmente e encontrar as informações necessárias de forma rápida e eficiente.",
    ],
    image: "/images/projects/quero+.png",
    stacks: ["Figma"],
    linkProjects: ["https://www.canva.com/design/DAFyQ0Bq6DE/CBjI0fAnLeb8K-YV-G0bKQ/edit?utm_content=DAFyQ0Bq6DE&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton", "", ""],
    software: false,
    design: true,
  }, 
 
];

export default projetos;
